version: "3"

services: 
  node:
    build:
      context: ./node
      dockerfile: Dockerfile.prod
    image: alefpassos/node:prod
    container_name: node
    networks:
      - nodenet
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: alefpassos/nginx:prod
    container_name: nginx
    networks:
      - nodenet
    ports: 
      - "8080:80"

networks:
  nodenet:
    driver: bridge